In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.3'

In [3]:
np.__version__

'2.2.6'

In [5]:
ice_cream=["Chocolate", "Vainilla", "Strawbrry", "Rum"]

In [7]:
pd.Series(ice_cream)

0    Chocolate
1     Vainilla
2    Strawbrry
3          Rum
dtype: object

In [11]:
lottery=[4,8,16,23,42]
pd.Series(lottery)

0     4
1     8
2    16
3    23
4    42
dtype: int64

In [10]:
registrations=[True, False, True, True]
pd.Series(registrations)

0     True
1    False
2     True
3     True
dtype: bool

In [13]:
webster = {"Perro": "an animal", "Bananas": "A delicious fruit"}

In [14]:
pd.Series(webster)

Perro              an animal
Bananas    A delicious fruit
dtype: object

# Intro to Methos

In [16]:
prices=[2.99, 23.5,78.9]

In [17]:
s= pd.Series(prices)

In [19]:
s.sum()

np.float64(105.39000000000001)

In [20]:
s.product()

np.float64(5543.9085000000005)

In [21]:
s.mean()

np.float64(35.13)

# Parameters and Arguments

In [22]:
fuits=["apple", "orange", "plum", "grape", "blueberry"]

In [23]:
weekdays= ["monday", "tuesday", "wednesday", "thursday", "friday"]

In [24]:
pd.Series(fuits,weekdays)

monday           apple
tuesday         orange
wednesday         plum
thursday         grape
friday       blueberry
dtype: object

In [26]:
pd.Series(data=fuits, index=weekdays)

monday           apple
tuesday         orange
wednesday         plum
thursday         grape
friday       blueberry
dtype: object

# Import Series with read_csv Method

In [27]:
pd.read_csv("DataSets/pokemon.csv")

        Pokemon     Type
0     Bulbasaur    Grass
1       Ivysaur    Grass
2      Venusaur    Grass
3    Charmander     Fire
4    Charmeleon     Fire
..          ...      ...
716     Yveltal     Dark
717     Zygarde   Dragon
718     Diancie     Rock
719       Hoopa  Psychic
720   Volcanion     Fire

[721 rows x 2 columns]

In [31]:
# Importar como serie 
pd.read_csv("DataSets/pokemon.csv", usecols=["Pokemon"]).squeeze(True)
# Importar como DataFrame
pd.read_csv("DataSets/pokemon.csv", usecols=["Pokemon"])

        Pokemon
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
..          ...
716     Yveltal
717     Zygarde
718     Diancie
719       Hoopa
720   Volcanion

[721 rows x 1 columns]

In [37]:
pokemon = pd.read_csv("DataSets/pokemon.csv", usecols=["Pokemon"]).squeeze(True)

In [33]:
pd.read_csv("DataSets/google_stock_price.csv")

      Stock Price
0           50.12
1           54.10
2           54.65
3           52.38
4           52.95
...           ...
3007       772.88
3008       771.07
3009       773.18
3010       771.61
3011       782.22

[3012 rows x 1 columns]

In [40]:
pd.read_csv("DataSets/google_stock_price.csv", usecols=["Stock Price"]).squeeze(True)

0        50.12
1        54.10
2        54.65
3        52.38
4        52.95
         ...
3007    772.88
3008    771.07
3009    773.18
3010    771.61
3011    782.22
Name: Stock Price, Length: 3012, dtype: float64

In [41]:
google = pd.read_csv("DataSets/google_stock_price.csv", usecols=["Stock Price"]).squeeze(True)

# The .head() and .tail() Methods

In [38]:
pokemon.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Pokemon, dtype: object

In [42]:
google.tail(3)

3009    773.18
3010    771.61
3011    782.22
Name: Stock Price, dtype: float64

# Python built-in Fuctions

In [44]:
len(pokemon)

721

In [46]:
len(google)

3012

In [48]:
type(pokemon)

pandas.core.series.Series

In [50]:
dir(pokemon)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_cacher',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [51]:
sorted(pokemon)

['Abomasnow',
 'Abra',
 'Absol',
 'Accelgor',
 'Aegislash',
 'Aerodactyl',
 'Aggron',
 'Aipom',
 'Alakazam',
 'Alomomola',
 'Altaria',
 'Amaura',
 'Ambipom',
 'Amoonguss',
 'Ampharos',
 'Anorith',
 'Arbok',
 'Arcanine',
 'Arceus',
 'Archen',
 'Archeops',
 'Ariados',
 'Armaldo',
 'Aromatisse',
 'Aron',
 'Articuno',
 'Audino',
 'Aurorus',
 'Avalugg',
 'Axew',
 'Azelf',
 'Azumarill',
 'Azurill',
 'Bagon',
 'Baltoy',
 'Banette',
 'Barbaracle',
 'Barboach',
 'Basculin',
 'Bastiodon',
 'Bayleef',
 'Beartic',
 'Beautifly',
 'Beedrill',
 'Beheeyem',
 'Beldum',
 'Bellossom',
 'Bellsprout',
 'Bergmite',
 'Bibarel',
 'Bidoof',
 'Binacle',
 'Bisharp',
 'Blastoise',
 'Blaziken',
 'Blissey',
 'Blitzle',
 'Boldore',
 'Bonsly',
 'Bouffalant',
 'Braixen',
 'Braviary',
 'Breloom',
 'Bronzong',
 'Bronzor',
 'Budew',
 'Buizel',
 'Bulbasaur',
 'Buneary',
 'Bunnelby',
 'Burmy',
 'Butterfree',
 'Cacnea',
 'Cacturne',
 'Camerupt',
 'Carbink',
 'Carnivine',
 'Carracosta',
 'Carvanha',
 'Cascoon',
 'Castform',
 'Caterpie',
 'Celebi',
 'Chandelure',
 'Chansey',
 'Charizard',
 'Charmander',
 'Charmeleon',
 'Chatot',
 'Cherrim',
 'Cherubi',
 'Chesnaught',
 'Chespin',
 'Chikorita',
 'Chimchar',
 'Chimecho',
 'Chinchou',
 'Chingling',
 'Cinccino',
 'Clamperl',
 'Clauncher',
 'Clawitzer',
 'Claydol',
 'Clefable',
 'Clefairy',
 'Cleffa',
 'Cloyster',
 'Cobalion',
 'Cofagrigus',
 'Combee',
 'Combusken',
 'Conkeldurr',
 'Corphish',
 'Corsola',
 'Cottonee',
 'Cradily',
 'Cranidos',
 'Crawdaunt',
 'Cresselia',
 'Croagunk',
 'Crobat',
 'Croconaw',
 'Crustle',
 'Cryogonal',
 'Cubchoo',
 'Cubone',
 'Cyndaquil',
 'Darkrai',
 'Darmanitan',
 'Darumaka',
 'Dedenne',
 'Deerling',
 'Deino',
 'Delcatty',
 'Delibird',
 'Delphox',
 'Deoxys',
 'Dewgong',
 'Dewott',
 'Dialga',
 'Diancie',
 'Diggersby',
 'Diglett',
 'Ditto',
 'Dodrio',
 'Doduo',
 'Donphan',
 'Doublade',
 'Dragalge',
 'Dragonair',
 'Dragonite',
 'Drapion',
 'Dratini',
 'Drifblim',
 'Drifloon',
 'Drilbur',
 'Drowzee',
 'Druddigon',
 'Ducklett',
 'Dugtrio',
 'Dunsparce',
 'Duosion',
 'Durant',
 'Dusclops',
 'Dusknoir',
 'Duskull',
 'Dustox',
 'Dwebble',
 'Eelektrik',
 'Eelektross',
 'Eevee',
 'Ekans',
 'Electabuzz',
 'Electivire',
 'Electrike',
 'Electrode',
 'Elekid',
 'Elgyem',
 'Emboar',
 'Emolga',
 'Empoleon',
 'Entei',
 'Escavalier',
 'Espeon',
 'Espurr',
 'Excadrill',
 'Exeggcute',
 'Exeggutor',
 'Exploud',
 "Farfetch'd",
 'Fearow',
 'Feebas',
 'Fennekin',
 'Feraligatr',
 'Ferroseed',
 'Ferrothorn',
 'Finneon',
 'Flaaffy',
 'Flabébé',
 'Flareon',
 'Fletchinder',
 'Fletchling',
 'Floatzel',
 'Floette',
 'Florges',
 'Flygon',
 'Foongus',
 'Forretress',
 'Fraxure',
 'Frillish',
 'Froakie',
 'Frogadier',
 'Froslass',
 'Furfrou',
 'Furret',
 'Gabite',
 'Gallade',
 'Galvantula',
 'Garbodor',
 'Garchomp',
 'Gardevoir',
 'Gastly',
 'Gastrodon',
 'Genesect',
 'Gengar',
 'Geodude',
 'Gible',
 'Gigalith',
 'Girafarig',
 'Giratina',
 'Glaceon',
 'Glalie',
 'Glameow',
 'Gligar',
 'Gliscor',
 'Gloom',
 'Gogoat',
 'Golbat',
 'Goldeen',
 'Golduck',
 'Golem',
 'Golett',
 'Golurk',
 'Goodra',
 'Goomy',
 'Gorebyss',
 'Gothita',
 'Gothitelle',
 'Gothorita',
 'Gourgeist',
 'Granbull',
 'Graveler',
 'Greninja',
 'Grimer',
 'Grotle',
 'Groudon',
 'Grovyle',
 'Growlithe',
 'Grumpig',
 'Gulpin',
 'Gurdurr',
 'Gyarados',
 'Happiny',
 'Hariyama',
 'Haunter',
 'Hawlucha',
 'Haxorus',
 'Heatmor',
 'Heatran',
 'Heliolisk',
 'Helioptile',
 'Heracross',
 'Herdier',
 'Hippopotas',
 'Hippowdon',
 'Hitmonchan',
 'Hitmonlee',
 'Hitmontop',
 'Ho-oh',
 'Honchkrow',
 'Honedge',
 'Hoopa',
 'Hoothoot',
 'Hoppip',
 'Horsea',
 'Houndoom',
 'Houndour',
 'Huntail',
 'Hydreigon',
 'Hypno',
 'Igglybuff',
 'Illumise',
 'Infernape',
 'Inkay',
 'Ivysaur',
 'Jellicent',
 'Jigglypuff',
 'Jirachi',
 'Jolteon',
 'Joltik',
 'Jumpluff',
 'Jynx',
 'Kabuto',
 'Kabutops',
 'Kadabra',
 'Kakuna',
 'Kangaskhan',
 'Karrablast',
 'Kecleon',
 'Keldeo',
 'Kingdra',
 'Kingler',
 'Kirlia',
 'Klang',
 'Klefki',
 'Klink',
 'Klinklang',
 'Koffing',
 'Krabby',
 'Kricketot',
 'Kricketune',
 'Krokorok',
 'Krookodile',
 'Kyogre',
 'Kyurem',
 'Lairon',
 'Lampent',
 'Landorus',
 'Lanturn',
 'Lapras',
 'Larvesta',
 'Larvitar',
 'Latias',
 'Latios',
 'Leafeon',
 'Leavanny',
 'Ledian',
 'Ledyba',
 'Lickilicky',
 'Lickitung',
 'Liepard',
 'Lileep',
 'Lilligant',
 'Lillipup',
 'Linoone',
 'Litleo',
 'Litwick',
 'Lombre',
 'Lopunny',
 'Lotad',
 'Loudred',
 'Lucario',
 'Ludicolo',
 'Lugia',
 'Lumineon',
 'Lunatone',
 'Luvdisc',
 'Luxio',
 'Luxray',
 'Machamp',
 'Machoke',
 'Machop',
 'Magby',
 'Magcargo',
 'Magikarp',
 'Magmar',
 'Magmortar',
 'Magnemite',
 'Magneton',
 'Magnezone',
 'Makuhita',
 'Malamar',
 'Mamoswine',
 'Manaphy',
 'Mandibuzz',
 'Manectric',
 'Mankey',
 'Mantine',
 'Mantyke',
 'Maractus',
 'Mareep',
 'Marill',
 'Marowak',
 'Marshtomp',
 'Masquerain',
 'Mawile',
 'Medicham',
 'Meditite',
 'Meganium',
 'Meloetta',
 'Meowstic',
 'Meowth',
 'Mesprit',
 'Metagross',
 'Metang',
 'Metapod',
 'Mew',
 'Mewtwo',
 'Mienfoo',
 'Mienshao',
 'Mightyena',
 'Milotic',
 'Miltank',
 'Mime Jr.',
 'Minccino',
 'Minun',
 'Misdreavus',
 'Mismagius',
 'Moltres',
 'Monferno',
 'Mothim',
 'Mr. Mime',
 'Mudkip',
 'Muk',
 'Munchlax',
 'Munna',
 'Murkrow',
 'Musharna',
 'Natu',
 'Nidoking',
 'Nidoqueen',
 'Nidoran',
 'Nidoran♂',
 'Nidorina',
 'Nidorino',
 'Nincada',
 'Ninetales',
 'Ninjask',
 'Noctowl',
 'Noibat',
 'Noivern',
 'Nosepass',
 'Numel',
 'Nuzleaf',
 'Octillery',
 'Oddish',
 'Omanyte',
 'Omastar',
 'Onix',
 'Oshawott',
 'Pachirisu',
 'Palkia',
 'Palpitoad',
 'Pancham',
 'Pangoro',
 'Panpour',
 'Pansage',
 'Pansear',
 'Paras',
 'Parasect',
 'Patrat',
 'Pawniard',
 'Pelipper',
 'Persian',
 'Petilil',
 'Phanpy',
 'Phantump',
 'Phione',
 'Pichu',
 'Pidgeot',
 'Pidgeotto',
 'Pidgey',
 'Pidove',
 'Pignite',
 'Pikachu',
 'Piloswine',
 'Pineco',
 'Pinsir',
 'Piplup',
 'Plusle',
 'Politoed',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Ponyta',
 'Poochyena',
 'Porygon',
 'Porygon-Z',
 'Porygon2',
 'Primeape',
 'Prinplup',
 'Probopass',
 'Psyduck',
 'Pumpkaboo',
 'Pupitar',
 'Purrloin',
 'Purugly',
 'Pyroar',
 'Quagsire',
 'Quilava',
 'Quilladin',
 'Qwilfish',
 'Raichu',
 'Raikou',
 'Ralts',
 'Rampardos',
 'Rapidash',
 'Raticate',
 'Rattata',
 'Rayquaza',
 'Regice',
 'Regigigas',
 'Regirock',
 'Registeel',
 'Relicanth',
 'Remoraid',
 'Reshiram',
 'Reuniclus',
 'Rhydon',
 'Rhyhorn',
 'Rhyperior',
 'Riolu',
 'Roggenrola',
 'Roselia',
 'Roserade',
 'Rotom',
 'Rufflet',
 'Sableye',
 'Salamence',
 'Samurott',
 'Sandile',
 'Sandshrew',
 'Sandslash',
 'Sawk',
 'Sawsbuck',
 'Scatterbug',
 'Sceptile',
 'Scizor',
 'Scolipede',
 'Scrafty',
 'Scraggy',
 'Scyther',
 'Seadra',
 'Seaking',
 'Sealeo',
 'Seedot',
 'Seel',
 'Seismitoad',
 'Sentret',
 'Serperior',
 'Servine',
 'Seviper',
 'Sewaddle',
 'Sharpedo',
 'Shaymin',
 'Shedinja',
 'Shelgon',
 'Shellder',
 'Shellos',
 'Shelmet',
 'Shieldon',
 'Shiftry',
 'Shinx',
 'Shroomish',
 'Shuckle',
 'Shuppet',
 'Sigilyph',
 'Silcoon',
 'Simipour',
 'Simisage',
 'Simisear',
 'Skarmory',
 'Skiddo',
 'Skiploom',
 'Skitty',
 'Skorupi',
 'Skrelp',
 'Skuntank',
 'Slaking',
 'Slakoth',
 'Sliggoo',
 'Slowbro',
 'Slowking',
 'Slowpoke',
 'Slugma',
 'Slurpuff',
 'Smeargle',
 'Smoochum',
 'Sneasel',
 'Snivy',
 'Snorlax',
 'Snorunt',
 'Snover',
 'Snubbull',
 'Solosis',
 'Solrock',
 'Spearow',
 'Spewpa',
 'Spheal',
 'Spinarak',
 'Spinda',
 'Spiritomb',
 'Spoink',
 'Spritzee',
 'Squirtle',
 'Stantler',
 'Staraptor',
 'Staravia',
 'Starly',
 'Starmie',
 'Staryu',
 'Steelix',
 'Stoutland',
 'Stunfisk',
 'Stunky',
 'Sudowoodo',
 'Suicune',
 'Sunflora',
 'Sunkern',
 'Surskit',
 'Swablu',
 'Swadloon',
 'Swalot',
 'Swampert',
 'Swanna',
 'Swellow',
 'Swinub',
 'Swirlix',
 'Swoobat',
 'Sylveon',
 'Taillow',
 'Talonflame',
 'Tangela',
 'Tangrowth',
 'Tauros',
 'Teddiursa',
 'Tentacool',
 'Tentacruel',
 'Tepig',
 'Terrakion',
 'Throh',
 'Thundurus',
 'Timburr',
 'Tirtouga',
 'Togekiss',
 'Togepi',
 'Togetic',
 'Torchic',
 'Torkoal',
 'Tornadus',
 'Torterra',
 'Totodile',
 'Toxicroak',
 'Tranquill',
 'Trapinch',
 'Treecko',
 'Trevenant',
 'Tropius',
 'Trubbish',
 'Turtwig',
 'Tympole',
 'Tynamo',
 'Typhlosion',
 'Tyranitar',
 'Tyrantrum',
 'Tyrogue',
 'Tyrunt',
 'Umbreon',
 'Unfezant',
 'Unown',
 'Ursaring',
 'Uxie',
 'Vanillish',
 'Vanillite',
 'Vanilluxe',
 'Vaporeon',
 'Venipede',
 'Venomoth',
 'Venonat',
 'Venusaur',
 'Vespiquen',
 'Vibrava',
 'Victini',
 'Victreebel',
 'Vigoroth',
 'Vileplume',
 'Virizion',
 'Vivillon',
 'Volbeat',
 'Volcanion',
 'Volcarona',
 'Voltorb',
 'Vullaby',
 'Vulpix',
 'Wailmer',
 'Wailord',
 'Walrein',
 'Wartortle',
 'Watchog',
 'Weavile',
 'Weedle',
 'Weepinbell',
 'Weezing',
 'Whimsicott',
 'Whirlipede',
 'Whiscash',
 'Whismur',
 'Wigglytuff',
 'Wingull',
 'Wobbuffet',
 'Woobat',
 'Wooper',
 'Wormadam',
 'Wurmple',
 'Wynaut',
 'Xatu',
 'Xerneas',
 'Yamask',
 'Yanma',
 'Yanmega',
 'Yveltal',
 'Zangoose',
 'Zapdos',
 'Zebstrika',
 'Zekrom',
 'Zigzagoon',
 'Zoroark',
 'Zorua',
 'Zubat',
 'Zweilous',
 'Zygarde']