# DataFrame III + Import Dataframe

In [1]:
import pandas as pd

In [4]:
b=pd.read_csv("Datasets/jamesbond.csv", index_col="Film")

In [5]:
actor=b.pop("Actor")

In [6]:
del b["Director"]

# Create random Sample

In [7]:
b=pd.read_csv("Datasets/jamesbond.csv", index_col="Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [8]:
b.sample()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5

In [12]:
b.sample(n=2)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

In [15]:
b.sample(frac=.23) # una muestra aleatoria del 23% del DataFrame

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN

In [20]:
b.sample(n=3, axis=0)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

In [23]:
b.sample(n=3, axis=1)

                                 Budget  Bond Actor Salary           Actor
Film
A View to a Kill                   54.5                9.1     Roger Moore
Casino Royale                     145.3                3.3    Daniel Craig
Casino Royale                      85.0                NaN     David Niven
Diamonds Are Forever               34.7                5.8    Sean Connery
Die Another Day                   154.2               17.9  Pierce Brosnan
Dr. No                              7.0                0.6    Sean Connery
For Your Eyes Only                 60.2                NaN     Roger Moore
From Russia with Love              12.6                1.6    Sean Connery
GoldenEye                          76.9                5.1  Pierce Brosnan
Goldfinger                         18.6                3.2    Sean Connery
Licence to Kill                    56.7                7.9  Timothy Dalton
Live and Let Die                   30.8                NaN     Roger Moore
Moonraker                          91.5                NaN     Roger Moore
Never Say Never Again              86.0                NaN    Sean Connery
Octopussy                          53.9                7.8     Roger Moore
On Her Majesty's Secret Service    37.3                0.6  George Lazenby
Quantum of Solace                 181.4                8.1    Daniel Craig
Skyfall                           170.2               14.5    Daniel Craig
Spectre                           206.3                NaN    Daniel Craig
The Living Daylights               68.8                5.2  Timothy Dalton
The Man with the Golden Gun        27.7                NaN     Roger Moore
The Spy Who Loved Me               45.1                NaN     Roger Moore
The World Is Not Enough           158.3               13.5  Pierce Brosnan
Thunderball                        41.9                4.7    Sean Connery
Tomorrow Never Dies               133.9               10.0  Pierce Brosnan
You Only Live Twice                59.9                4.4    Sean Connery

In [25]:
b.sample(n=2, axis=1)

                                 Bond Actor Salary  Box Office
Film
A View to a Kill                               9.1       275.2
Casino Royale                                  3.3       581.5
Casino Royale                                  NaN       315.0
Diamonds Are Forever                           5.8       442.5
Die Another Day                               17.9       465.4
Dr. No                                         0.6       448.8
For Your Eyes Only                             NaN       449.4
From Russia with Love                          1.6       543.8
GoldenEye                                      5.1       518.5
Goldfinger                                     3.2       820.4
Licence to Kill                                7.9       250.9
Live and Let Die                               NaN       460.3
Moonraker                                      NaN       535.0
Never Say Never Again                          NaN       380.0
Octopussy                                      7.8       373.8
On Her Majesty's Secret Service                0.6       291.5
Quantum of Solace                              8.1       514.2
Skyfall                                       14.5       943.5
Spectre                                        NaN       726.7
The Living Daylights                           5.2       313.5
The Man with the Golden Gun                    NaN       334.0
The Spy Who Loved Me                           NaN       533.0
The World Is Not Enough                       13.5       439.5
Thunderball                                    4.7       848.1
Tomorrow Never Dies                           10.0       463.2
You Only Live Twice                            4.4       514.2

# The .nsmallest() and .nlargest() Methods

In [27]:
b=pd.read_csv("Datasets/jamesbond.csv", index_col="Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [28]:
b.sort_values("Box Office", ascending=False).head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [30]:
b.nlargest(3,columns="Box Office")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [34]:
b.nsmallest(n=2, columns="Box Office")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1

In [36]:
b.nsmallest(6, columns="Bond Actor Salary")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [38]:
b["Box Office"].nlargest(8)

Film
Skyfall                  943.5
Thunderball              848.1
Goldfinger               820.4
Spectre                  726.7
Casino Royale            581.5
From Russia with Love    543.8
Moonraker                535.0
The Spy Who Loved Me     533.0
Name: Box Office, dtype: float64

In [41]:
b["Year"].nsmallest(2) # Peliculas más antiguas

Film
Dr. No                   1962
From Russia with Love    1963
Name: Year, dtype: int64

# Filterring with the where Method

In [43]:
b=pd.read_csv("Datasets/jamesbond.csv", index_col="Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [44]:
mask=b["Actor"]=="Sean Connery"

In [45]:
b[mask]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [48]:
b.where(mask)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [49]:
b.where(b["Box Office"]>800)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,NaN,NaN,NaN,NaN,NaN,NaN
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,NaN,NaN,NaN,NaN,NaN,NaN
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,NaN,NaN,NaN,NaN,NaN,NaN
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,NaN,NaN,NaN,NaN,NaN,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,2012.0,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
mask2=b.where(b["Box Office"]>800)

# The .query() Method

In [53]:
b=pd.read_csv("Datasets/jamesbond.csv", index_col="Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [59]:
b.columns=[column_name.replace(" ", "_")for column_name in b.columns]
b.head(1)

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1

In [61]:
b.query('Actor=="Sean Connery"')

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [65]:
b.query('Director=="Terence Young"')

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7

In [67]:
b.query("Actor!= 'Roger Moore'")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [68]:
b.query("Actor != 'Roger Moore' and Director=='John Glen'")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2

In [69]:
b.query("Actor in ['Timothy Dalton', 'George Lazenby']")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2

In [70]:
b.query("Actor not in ['Timothy Dalton', 'George Lazenby']")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

# A review of the .apply() Method on Single Columns

In [72]:
b=pd.read_csv("Datasets/jamesbond.csv", index_col="Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [76]:
def conver_to_string_and_add_millions(number):
    return str(number)+" Millions" # Transform a numeric input to a str 

b["Box Office"]=b["Box Office"].apply(conver_to_string_and_add_millions)

In [77]:
b

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2Millions Millions,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5Millions Millions,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0Millions Millions,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5Millions Millions,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4Millions Millions,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8Millions Millions,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4Millions Millions,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8Millions Millions,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5Millions Millions,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4Millions Millions,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9Millions Millions,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3Millions Millions,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0Millions Millions,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0Millions Millions,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8Millions Millions,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5Millions Millions,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2Millions Millions,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5Millions Millions,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7Millions Millions,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5Millions Millions,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0Millions Millions,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0Millions Millions,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5Millions Millions,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1Millions Millions,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2Millions Millions,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2Millions Millions,59.9,4.4

# The .isnull() Method

In [3]:
df = pd.read_csv("Datasets/employees.csv")
#df["Senior Management"] = df["Senior Management"] as type

In [5]:
mask = df["Team"].isnull()

In [7]:
df[mask]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
32,NaN,Male,8/21/1998,2:27 PM,122340,6.417,NaN,NaN
91,James,NaN,1/26/2005,11:00 PM,128771,8.309,False,NaN
109,Christopher,Male,4/22/2000,10:15 AM,37919,11.449,False,NaN
139,NaN,Female,10/3/1990,1:08 AM,132373,10.527,NaN,NaN
199,Jonathan,Male,7/17/2009,8:15 AM,130581,16.736,True,NaN
258,Michael,Male,1/24/2002,3:04 AM,43586,12.659,False,NaN
290,Jeremy,Male,6/14/1988,6:20 PM,129460,13.657,True,NaN
314,Bobby,Male,3/31/1996,5:40 PM,112117,6.338,False,NaN
367,Edward,Male,8/4/1989,6:06 AM,66067,10.957,True,NaN
382,NaN,Female,4/18/1996,3:57 PM,107024,12.182,NaN,NaN
434,Joyce,Female,2/7/1995,7:38 AM,50701,14.227,True,NaN
438,Jason,Male,11/20/1998,2:54 PM,69244,6.220,True,NaN
445,Chris,Male,12/12/2006,1:57 AM,71642,1.496,False,NaN
479,Richard,Male,7/4/1997,11:47 AM,47647,18.787,True,NaN
512,Wanda,Female,4/6/1993,3:11 AM,78883,19.695,False,NaN
513,Jimmy,Male,11/19/2013,7:29 PM,63549,19.624,False,NaN
520,Peter,Male,2/22/2003,9:09 AM,56580,8.411,True,NaN
567,NaN,Female,4/1/1980,8:04 PM,48141,12.605,NaN,NaN
573,Kimberly,Female,12/30/1981,4:51 AM,81800,5.435,True,NaN
580,Harry,Male,1/27/1985,8:18 PM,65482,18.089,False,NaN
626,NaN,Female,4/13/1997,8:03 AM,131755,2.930,NaN,NaN
634,Carl,Male,3/30/1987,5:59 PM,75598,19.289,False,NaN
635,Randy,Male,9/27/2000,3:04 AM,89831,13.047,True,NaN
647,Donald,Male,4/6/1988,10:00 AM,122920,5.320,False,NaN
669,Joseph,NaN,3/28/1982,1:05 PM,86564,11.879,True,NaN
684,Alice,Female,1/21/2016,5:07 PM,117787,10.485,False,NaN
706,Todd,Male,7/4/1993,6:53 PM,128175,18.473,True,NaN
726,Daniel,Male,2/29/2016,4:04 AM,77287,13.000,True,NaN
753,Antonio,Male,6/6/1999,10:54 PM,41928,5.478,True,NaN
774,NaN,Female,6/18/2000,7:36 AM,106428,10.867,NaN,NaN
781,Lawrence,Male,7/3/1995,10:55 PM,46378,9.127,False,NaN
794,Nicole,Female,3/1/2004,5:17 PM,44021,10.286,False,NaN
826,NaN,NaN,8/1/1988,1:35 AM,87103,5.665,NaN,NaN
850,Charles,Male,9/3/1997,10:04 AM,148291,6.002,False,NaN
851,Bobby,Male,8/19/1996,1:16 AM,147842,16.158,True,NaN
853,Mildred,Female,4/6/2007,10:06 PM,139284,11.390,True,NaN
855,Phillip,NaN,10/20/2003,11:09 AM,89700,2.277,True,NaN
864,Ryan,Male,11/16/2012,1:47 PM,57292,6.010,False,NaN
912,Joe,Male,12/8/1998,10:28 AM,126120,1.020,False,NaN
951,NaN,Female,9/14/2010,5:19 AM,143638,9.662,NaN,NaN

In [9]:
condition = df["Gender"].notnull()

In [11]:
df[condition]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

# The between Method

In [12]:
mask = df["Salary"].between(60000,70000)

In [14]:
df[mask]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal
41,Christine,NaN,6/28/2015,1:08 AM,66582,11.308,True,Business Development
...,...,...,...,...,...,...,...,...
965,Catherine,Female,9/25/1989,1:31 AM,68164,18.393,False,Client Services
970,Alice,Female,9/3/1988,8:54 PM,63571,15.397,True,Product
974,Harry,Male,8/30/2011,6:31 PM,67656,16.455,True,Client Services
978,Sean,Male,1/17/1983,2:23 PM,66146,11.178,False,Human Resources
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development

In [15]:
df[df["Bonus %"].between(2.0, 5.0)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal
40,Michael,Male,10/10/2008,11:25 AM,99283,2.665,True,Distribution
49,Chris,NaN,1/24/1980,12:13 PM,113590,3.055,False,Sales
60,Paula,NaN,11/23/2005,2:01 PM,48866,4.271,False,Distribution
...,...,...,...,...,...,...,...,...
943,Wayne,Male,9/8/2006,11:09 AM,67471,2.728,False,Engineering
961,Antonio,NaN,6/18/1989,9:37 PM,103050,3.050,False,Legal
976,Denise,Female,10/19/1992,5:42 AM,137954,4.195,True,Legal
989,Justin,NaN,2/10/1991,4:58 PM,38344,3.794,False,Legal
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing

# The .drop_duplicates() Method

In [17]:
len(df)

1000

In [23]:
df.drop_duplicates(subset= ["First Name"], inplace=True)

In [21]:
df.drop_duplicates(subset= ["First Name"], keep="first")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
712,Martin,NaN,2/6/2001,4:17 AM,123963,15.745,True,Engineering
749,Janet,NaN,1/25/1986,5:48 AM,85789,9.712,False,Legal
832,Keith,Male,2/12/2003,3:02 PM,120672,19.467,False,Legal
855,Phillip,NaN,10/20/2003,11:09 AM,89700,2.277,True,NaN
887,David,Male,12/5/2009,8:48 AM,92242,15.407,False,Legal

In [24]:
len(df)

201