In [2]:
import pandas as pd

In [48]:
employees = pd.read_csv("Datasets/employees.csv", index_col="First Name", parse_dates=["Start Date"])
employees.sort_index(inplace=True)

In [49]:
employees

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Aaron,Male,2012-02-17,10:20 AM,61602,11.849,True,Marketing
Aaron,Male,1994-01-29,6:48 PM,58755,5.097,True,Marketing
Aaron,Male,1990-07-22,2:53 PM,52119,11.343,True,Client Services
Aaron,NaN,1986-01-22,7:39 PM,63126,18.424,False,Client Services
Adam,Male,2011-05-21,1:45 AM,95327,15.120,False,Distribution
...,...,...,...,...,...,...,...
NaN,Male,2001-05-23,7:52 PM,103877,6.322,NaN,Distribution
NaN,Female,2000-08-23,4:19 PM,95866,19.388,NaN,Sales
NaN,Female,1985-09-15,1:50 AM,133472,16.941,NaN,Distribution
NaN,Male,2012-07-30,3:07 PM,107351,5.329,NaN,Marketing
NaN,Female,2010-09-14,5:19 AM,143638,9.662,NaN,NaN

In [ ]:
# Generar un reporte con filtros que contengan los registros de los empleados masculinos y marketing

In [50]:
employees.query("Gender=='Male' and Team=='Marketing'").head()

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Aaron,Male,2012-02-17,10:20 AM,61602,11.849,True,Marketing
Aaron,Male,1994-01-29,6:48 PM,58755,5.097,True,Marketing
Arthur,Male,2014-12-16,4:56 PM,66819,6.639,True,Marketing
Benjamin,Male,1984-09-11,6:37 AM,84810,15.794,False,Marketing
Charles,Male,2004-09-14,8:13 PM,107391,1.260,True,Marketing

In [64]:
#filtrar empleados que son parte de Senior management o que empezaron antes del 1990

mask1 = employees["Senior Management"]= True
mask2 = employees["Start Date"]<"12-31-1989"
#employees[mask2]
employees[(mask1) | (mask2)]

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Aaron,Male,2012-02-17,10:20 AM,61602,11.849,True,Marketing
Aaron,Male,1994-01-29,6:48 PM,58755,5.097,True,Marketing
Aaron,Male,1990-07-22,2:53 PM,52119,11.343,True,Client Services
Aaron,NaN,1986-01-22,7:39 PM,63126,18.424,True,Client Services
Adam,Male,2011-05-21,1:45 AM,95327,15.120,True,Distribution
...,...,...,...,...,...,...,...
NaN,Male,2001-05-23,7:52 PM,103877,6.322,True,Distribution
NaN,Female,2000-08-23,4:19 PM,95866,19.388,True,Sales
NaN,Female,1985-09-15,1:50 AM,133472,16.941,True,Distribution
NaN,Male,2012-07-30,3:07 PM,107351,5.329,True,Marketing
NaN,Female,2010-09-14,5:19 AM,143638,9.662,True,NaN

In [57]:
pd.__version__

'2.3.3'

In [ ]:
# Filtrar los empleados que se llaman Robert, 
# que son parte de client Services o que empezaron despues de junio de 2016